### PR TITLE
Add support for autowiring with Annotated

### PR DESCRIPTION
**Pull request by lozanocampillod**
## What does this PR do?

This PR adds the feature addressed at issue https://github.com/roo-oliv/injectable/issues/108

### Context

I use injectable in production but when using a static type checker (mypy in our case) the Autowiring(T) type is not detected by mypy. This PR lets inject dependencies in the style proposted in the accepted solution of the aforementioned issue.

```python
@autowired
def foo(service: Autowired(Service)): ...
```

```python
@autowired
def foo(service: Annotated[Autowired(Service), foo, bar]): ...
```

```python
@autowired
def foo(service: Annotated[foo, Autowired(Service), bar]): ...
```

### CODE REVIEW

**Review by andrsdt — APPROVED** [review]

**Comment by mjunyent** [comment]
@andrsdt could this be merged? Is the library still supported?

**Comment by roo-oliv** [comment]
Hi, @lozanocampillod! Thanks a lot for contributing back to the project ❤️  It means a lot to me :)

I'm sorry for the delay, I was unwell and couldn't get to this earlier.

I'll build the project locally and perform some tests before merging, that should be quick ;)

**Comment by roo-oliv** [comment]
> @roo-oliv could this be merged? Is the library still supported?

Yes! The lib is supported! I'm the only maintainer, which makes things slower, especially when I'm overloaded or ill but I try my best to make things simple and fast!

**Review by roo-oliv — APPROVED** [review]
The code looks good and thanks for the tests!

I'll merge this and add more tests and documentation and then release a new version to PyPI soon!

**Comment by lozanocampillod** [comment]
Thanks for your review! Nice to see the library is still supported and that I'll be able to keep using it in my projects!

**Comment by roo-oliv** [comment]
@lozanocampillod and all, just letting you know that [Injectable 4.0.0 was just released](https://github.com/roo-oliv/injectable/releases/tag/4.0.0) with support for the use of Annotated! 🎉

**Pull request merged**
